name:                minesweepin
version:             0.1.0.0
github:              "ConorClery/minesweeper"
license:             BSD3
author:              "Conor"
maintainer:          "cleryc@tcd.ie"
copyright:           "2019 Conor Clery Productions Ltd."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/minesweepin#readme>

dependencies:
- base >= 4.7 && < 5
- random
- threepenny-gui
- debug

library:
  source-dirs: src

executables:
  minesweepin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minesweepin

tests:
  minesweepin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minesweepin
    - hspec
    - hspec-core
    - hspec-expectations
    - QuickCheck
